apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-notizblock-app-chart.fullname" . }}-config
data:
  BACKEND_URL: "http://{{ include "my-notizblock-app-chart.fullname" . }}-backend.default.svc.cluster.local:3000"