apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-notizblock-app-chart.fullname" . }}-db-secret
  labels:
    app: {{ include "my-notizblock-app-chart.fullname" . }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}