apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-notizblock-app-chart.fullname" . }}-frontend
  labels:
    app: {{ include "my-notizblock-app-chart.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-notizblock-app-chart.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "my-notizblock-app-chart.fullname" . }}-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://another-helm-release-my-notizblock-app-chart-backend:3000"