# .github/workflows/ci.yml

name: Notizblock CI Pipeline

on:
  push:
    branches: [ "main", "master" ] # Oder dein Hauptbranch
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-push-frontend:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend # Pfad zum Dockerfile-Verzeichnis
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/notizblock-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/notizblock-frontend:${{ github.sha }}
          # Optional: Build-Argumente übergeben
          # build-args: |
          #   VITE_API_URL=https://api.example.com # Oder ein Secret hierfür

